// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CommsClient is the client API for Comms service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CommsClient interface {
	SendAccountInfo(ctx context.Context, in *AccountInfo, opts ...grpc.CallOption) (*AccountResponse, error)
	SendPost(ctx context.Context, in *PostInfo, opts ...grpc.CallOption) (*PostReply, error)
	DoesAccountExist(ctx context.Context, in *AccountInfo, opts ...grpc.CallOption) (*AccountResponse, error)
}

type commsClient struct {
	cc grpc.ClientConnInterface
}

func NewCommsClient(cc grpc.ClientConnInterface) CommsClient {
	return &commsClient{cc}
}

func (c *commsClient) SendAccountInfo(ctx context.Context, in *AccountInfo, opts ...grpc.CallOption) (*AccountResponse, error) {
	out := new(AccountResponse)
	err := c.cc.Invoke(ctx, "/proto.Comms/SendAccountInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commsClient) SendPost(ctx context.Context, in *PostInfo, opts ...grpc.CallOption) (*PostReply, error) {
	out := new(PostReply)
	err := c.cc.Invoke(ctx, "/proto.Comms/SendPost", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commsClient) DoesAccountExist(ctx context.Context, in *AccountInfo, opts ...grpc.CallOption) (*AccountResponse, error) {
	out := new(AccountResponse)
	err := c.cc.Invoke(ctx, "/proto.Comms/DoesAccountExist", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CommsServer is the server API for Comms service.
// All implementations must embed UnimplementedCommsServer
// for forward compatibility
type CommsServer interface {
	SendAccountInfo(context.Context, *AccountInfo) (*AccountResponse, error)
	SendPost(context.Context, *PostInfo) (*PostReply, error)
	DoesAccountExist(context.Context, *AccountInfo) (*AccountResponse, error)
	mustEmbedUnimplementedCommsServer()
}

// UnimplementedCommsServer must be embedded to have forward compatible implementations.
type UnimplementedCommsServer struct {
}

func (UnimplementedCommsServer) SendAccountInfo(context.Context, *AccountInfo) (*AccountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendAccountInfo not implemented")
}
func (UnimplementedCommsServer) SendPost(context.Context, *PostInfo) (*PostReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendPost not implemented")
}
func (UnimplementedCommsServer) DoesAccountExist(context.Context, *AccountInfo) (*AccountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DoesAccountExist not implemented")
}
func (UnimplementedCommsServer) mustEmbedUnimplementedCommsServer() {}

// UnsafeCommsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CommsServer will
// result in compilation errors.
type UnsafeCommsServer interface {
	mustEmbedUnimplementedCommsServer()
}

func RegisterCommsServer(s grpc.ServiceRegistrar, srv CommsServer) {
	s.RegisterService(&Comms_ServiceDesc, srv)
}

func _Comms_SendAccountInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccountInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommsServer).SendAccountInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Comms/SendAccountInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommsServer).SendAccountInfo(ctx, req.(*AccountInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _Comms_SendPost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommsServer).SendPost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Comms/SendPost",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommsServer).SendPost(ctx, req.(*PostInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _Comms_DoesAccountExist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccountInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommsServer).DoesAccountExist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Comms/DoesAccountExist",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommsServer).DoesAccountExist(ctx, req.(*AccountInfo))
	}
	return interceptor(ctx, in, info, handler)
}

// Comms_ServiceDesc is the grpc.ServiceDesc for Comms service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Comms_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Comms",
	HandlerType: (*CommsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendAccountInfo",
			Handler:    _Comms_SendAccountInfo_Handler,
		},
		{
			MethodName: "SendPost",
			Handler:    _Comms_SendPost_Handler,
		},
		{
			MethodName: "DoesAccountExist",
			Handler:    _Comms_DoesAccountExist_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/communication.proto",
}
